config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :posts
  get 'sessions/new'

#login
  get    '/login',   to: 'sessions#new', as:'login'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/denied',to: 'sessions#on_denied',as: 'denied'

  resources :users
  #resources :tasks
  resources :projects, :path => '/' do
    resources :tasks do
   		post '/member/:uid' => 'tasks#add_member_to_task', as: 'add_member'
    end
    post '/add_member/:uid' => 'projects#add_member', as: 'add_member'
    post '/finish' => 'projects#finish_project', as: 'finish'
    get '/report' => 'projects#get_report', as: 'report'
  end

  # root to '#projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project

	has_many :participations_users
	has_many :users, through: :participations_users

	scope :idle, -> { left_outer_joins(:participations_users).where( participations_users: { id: nil} ) }

	scope :pending_by_user, lambda { |user|
		left_outer_joins(:participations_users).where(completed: false).where( participations_users: { user_id: user.id })
	}

	scope :by_user, lambda { |user|
		left_outer_joins(:participations_users).where( participations_users: { user_id: user.id })
	}

	scope :not_by_user, lambda { |user|
		where.not(id: by_user(user)).where.not(id: idle)
	}

	scope :completed, -> { where(completed: true) }

  scope :with_report, -> { where("length(tasks.task_report) > 0")}
	mount_uploader :image, ImageUploader
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_filter :load_project

  # GET /tasks
  # GET /tasks.json
  def index
    @users = User.all
    @tasks = @project.tasks.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @users = User.all
#@task = @project.tasks.find(params[:id])
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html
      format.json { render :json => { :task => @task, :location => [@project, @task] }, :include => {:users => {:only => :id}} }
    end
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
    @task = @project.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)
    members_array = params[:task][:list_members]

    update_task_members(members_array)

    respond_to do |format|
      if @task.save
        format.html { redirect_to [@project], notice: 'Atividade criada com sucesso' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update

    members_array = params[:task][:list_members]

    update_task_members(members_array)

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to [@project], notice: 'Atividade atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy
   # respond_to do |format|
   #   format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
   #   format.json { head :no_content }
   # end
  end

  # POST /:project_id/:task_id/add_member_to_task/:uid
  def add_member_to_task
    @task = @project.tasks.find(params[:task_id])
    add_member(params[:uid], @task)

    redirect_to [@project]
  end

  def add_member(member_id, task)
    user_member = User.find(member_id)


    if user_member.tasks.exists?(task) 
      user_member.tasks.delete(task)
    else
      user_member.tasks << task
    end
  end

  def update_task_members(members_id)
    @task.users.delete(@task.users)
    if members_id
      members_id.each do |member_id|
        member = User.find(member_id)
        if !member.tasks.exists?(@task)
          add_member(member_id, @task)
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :final_date, :task_report)
    end

    def load_project
      @project = Project.find(params[:project_id])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task]) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :final_date %>
    <%= f.date_select :final_date %>
  </div>

  <div class="field">
    <%= f.label :task_report %>
    <%= f.text_field :task_report %>
  </div>

  <div class="field">
    add an image....
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', project_task_path(@project, @task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project</h1>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<p>
  <strong>Final date:</strong>
  <%= @project.final_date %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>


<h1>Users</h1>
 <ul>
  <% @users.each do |user| %>
    <li>
    <%= link_to user.first_name ? user.first_name : user.cpf, project_add_member_path(@project,user), method: :post %>
    <%= user.projects.exists?(@project) ? 'Associado ao projeto' : 'Não associado ao projeto' %>
    </li>
  <% end %>
</ul>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Final date</th>
      <th>Task report</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.final_date %></td>
        <td><%= task.task_report %></td>
        <td><%= link_to 'Show', project_task_path(@project, task) %></td>
        <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
        <td><%= link_to 'Destroy', [@project, task], confirm: 'Are you sure?', method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_project_task_path(@project) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Final date:</strong>
  <%= @task.final_date %>
</p>

<p>
  <strong>Task report:</strong>
  <%= @task.task_report %>
</p>

<%= link_to 'Edit', edit_project_task_path(@project, @task) %> |
<%= link_to 'Back', project_tasks_path(@project) %>




<h1>Users</h1>


 <ul>
  <% @users.each do |user| next if !user.projects.exists?(@project) %>
	    <li>
	    <%= link_to user.first_name ? user.first_name : user.cpf, project_task_add_member_path(@project, @task, user), method: :post %>
	    <%= user.tasks.exists?(@task) ? 'Faz parte' : 'Nao faz parte'%>
	    </li>
  <% end %>
</ul>