config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :posts
  get 'sessions/new'

#login
  get    '/login',   to: 'sessions#new', as:'login'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/denied',to: 'sessions#on_denied',as: 'denied'

  resources :users
  #resources :tasks
  resources :projects, :path => '/' do
    resources :tasks do
   		post '/member/:uid' => 'tasks#add_member_to_task', as: 'add_member'
    end
    post '/add_member/:uid' => 'projects#add_member', as: 'add_member'
    post '/finish' => 'projects#finish_project', as: 'finish'
    get '/report' => 'projects#get_report', as: 'report'
  end

  # root to '#projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :participations
	has_many :projects, through: :participations

	has_many :participations_users
	has_many :tasks, through: :participations_users
	validates_uniqueness_of :cpf
	has_secure_password

	def full_name
		full_name = ""
		if self.first_name
			full_name += self.first_name + " "
		end

		if self.last_name
			full_name += self.last_name
		end

		return full_name
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:new, :edit, :create, :destroy]

  # GET /users
  # GET /users.json
  def index
    @page_name = "Ediquê - Usuários"
    @users = User.order('first_name ASC, last_name ASC')
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @page_name = "Ediquê - #{@user.full_name}"
    @current_projects = @user.projects.not_finished
    @past_projects = @user.projects.finished
  end

  # GET /users/new
  def new
    @page_name = "Ediquê - Criar usuário"
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:cpf, :first_name, :last_name, :admin, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %>
    <%= f.text_field :cpf %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>


  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>


  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :admin %>
    <%= f.check_box :admin%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 text-center">
			<h1>Usuários</h1>
		</div>
	</div>

	<div class="row">
		<div class="col-md-1"></div>
		<% @users.each do |user| %>
			<div class="col-md-2">
				<a href=<%= user_path(user) %>>
					<div class="thumbnail">
						<img src="https://goo.gl/OYC0MS" alt="...">
						<div class="caption">
							<h5 class="text-center"><%= user.full_name %></h5>
						</div>
					</div>
				</a>
			</div>
		<% end %>
		<div class="col-md-1"></div>
	</div>
</div>

<table>
	<thead>
		<tr>
			<th>Cpf</th>
			<th>First name</th>
			<th>Last name</th>
			<th>Email</th>
			<th>Admin</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= user.cpf %></td>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= user.email %></td>
				<td><%= user.admin %></td>
				<td><%= link_to 'Show', user %></td>
				<td><%= link_to 'Edit', edit_user_path(user) %></td>
				<td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3">
			<div class="well">
				<img src="https://goo.gl/OYC0MS" alt="Foto do usuário" class="img-responsive">
				<h2><%= @user.full_name %></h2>

				<h4>Email</h4>
				<p><%= @user.email %></p>

				<h4>CPF</h4>
				<p><%= @user.cpf %></p>
			</div>
		</div>

		<div class="col-md-9">
			<div class="well">
				<h3>PROJETOS EM ANDAMENTO</h3>
				<% if @current_projects.count > 0 %>
					<table class="table table-hover">
						<thead>
							<tr>
								<th>Projeto</th>
								<th>Atividades pendentes</th>
							</tr>
						</thead>
						<tbody>
							<% @current_projects.each do |proj| %>
							<tr>
								<td>
									<a href=<%=project_path(proj)%>> <%= proj.name %> </a>
								</td>
								<td><%= proj.tasks.pending_by_user(@user).count %></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<p>Nenhum projeto</p>
				<% end %>
			</div>

			<div class="well">
				<h3>PROJETOS PASSADOS</h3>
				<% if @past_projects.count > 0 %>
					<table class="table table-hover">
						<thead>
							<tr>
								<th>Projeto</th>
								<th>Atividades pendentes</th>
							</tr>
						</thead>
						<tbody>
							<% @past_projects.each do |proj| %>
							<tr>
								<td>
									<a href=<%=project_path(proj)%>> <%= proj.name %> </a>
								</td>
								<td><%= proj.tasks.pending_by_user(@user).count%></td>
							</tr>
							<% end %>
						</tbody>
					</table>
				<% else %>
					<p>Nenhum projeto</p>
				<% end %>
			</div>
		</div>
	</div>
</div>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>