config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  resources :posts
  get 'sessions/new'

#login
  get    '/login',   to: 'sessions#new', as:'login'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/denied',to: 'sessions#on_denied',as: 'denied'

  resources :users
  #resources :tasks
  resources :projects, :path => '/' do
    resources :tasks do
   		post '/member/:uid' => 'tasks#add_member_to_task', as: 'add_member'
    end
    post '/add_member/:uid' => 'projects#add_member', as: 'add_member'
    post '/finish' => 'projects#finish_project', as: 'finish'
    get '/report' => 'projects#get_report', as: 'report'
  end

  # root to '#projects#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :tasks
	has_many :participations
	has_many :users, through: :participations
  validates_uniqueness_of :name

	scope :finished, -> { where(finished: true) }
	scope :not_finished, -> { where(finished: false) }

	def progress_percent
		tasks_count = self.tasks.count

		if tasks_count == 0
			return 0
		end

		completed_tasks_count = self.tasks.completed.count

		return 100*completed_tasks_count/tasks_count
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.not_finished.includes(:tasks).includes(:users)
    @users = User.order('first_name ASC, last_name ASC')
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @page_name = "Ediquê - #{@project.name}"
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params(params))

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_url, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
        user_params = project_user_params(params)
        if(user_params && user_params[:ids])
          user_params[:ids].each do |user_id|
            add_member_to(@project, User.find(user_id))
          end
        end
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params(params))
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #GET /projects/:project_id/report
  def get_report
    @tasks = Project.find(params[:project_id]).tasks
    render("report")
  end

  # POST /projects/:project_id/add_member/:uid
  def add_member

    @project = Project.find(params[:project_id])
    user_member = User.find(params[:uid])

    add_member_to(@project, user_member)

    redirect_to controller: 'tasks', action: 'index'
  end

  def finish_project
    project = Project.find(params[:project_id])
    project.finished = true

    respond_to do |format|
      if project.save
        format.html { redirect_to projects_url, notice: 'Projeto arquivado com sucesso.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params(params)
      params.require(:project).permit(:name, :description, :start_date, :final_date)
    end
    def project_user_params(params)
      params.permit(:project_user_data).permit(:ids=>[])
    end
    def add_member_to(project, member)
      if member.projects.exists?(project)
        member.projects.delete(project)

        member.tasks.delete_all
      else
        member.projects << project
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :final_date %>
    <%= f.date_select :final_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container-fluid">

	<% @projects.each do |project| %>
		<!-- Single project container -->
		<div class="row">
			<div class="col-md-10 col-md-offset-1">
				<a href=<%= project_path(id: project) %>><div class="well project-well" id=<%= "project-#{project.id}" %>>
					<div class="row">
						<div class="project-item col-md-3 right-bordered">
							<h2><%= project.name %></h2>
							<p>Data final: <%= project.final_date.to_formatted_s(:pt_br) %></p>

							<div class="progress">
								<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow=<%= project.progress_percent %> aria-valuemin="0" aria-valuemax="100" style="width: <%= project.progress_percent %>%">
								</div>
							</div>
						</div>

						<div class="project-item col-md-3 right-bordered">
							<h3>Atividades</h3>
							<ul class="list-group activities-list">
								<li class="list-group-item">
									<span><%= project.tasks.by_user(current_user).count %></span>
									 tarefa<% if project.tasks.by_user(current_user).count != 1 %>s<%end%> para você
								</li>

								<li class="list-group-item">
									<span><%= project.tasks.idle.count %></span>
									 tarefa<% if project.tasks.idle.count != 1 %>s<%end%> ociosa<% if project.tasks.idle.count != 1 %>s<%end%>
								</li>
								<li class="list-group-item">
									<span><%= project.tasks.completed.count %></span>
									 tarefa<% if project.tasks.completed.count != 1 %>s<%end%> concluída<% if project.tasks.completed.count != 1 %>s<%end%>
								</li>
							</ul>
						</div>

						<div class="project-item col-md-6">
							<h3>Membros</h3>
							<ul class="list-group">
								<% project.users.each do |user| %>
									<li class="list-group-item">
										<%= user.full_name %></h4>
									</li>
								<% end %>
							</ul>
						</div>

					</div>
				</div></a>
			</div>
		</div>
	<% end %>
</div>

<a data-toggle="modal" href="#new-proj-modal" class="btn btn-danger btn-fab floating-btn">
	<i class="material-icons">add</i><div class="ripple-container"></div>
</a>


<div class="modal fade" id="new-proj-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="/" method="post">
				<!-- <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Novo projeto</h4>
				</div> -->
				<div class="modal-body">
					<div class="row">
						<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
						<div class="col-md-12">
							<div class="form-group form-group-lg label-floating">
								<label for="project[name]" class="control-label">Título do Projeto</label>
								<input type="text" class="form-control" id="project[name]" name="project[name]">
							</div>

							<div class="form-group label-floating">
								<label for="project[description]" class="control-label">Descrição</label>
								<textarea id="project[description]" name="project[description]" class="form-control"></textarea>
							</div>
						</div>
            <div class="col-md-6">
              <div class="form-group form-group-lg">
                <%@users.each do |user| %>
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" value=<%= "#{user.id}" %> name="project_user_data[ids][]">
                      <%= user.full_name %>
                    </label>
                  </div>
                <%end%>
              </div>
            </div>
						<div class="col-md-6 ">
							<div class="form-group form-group-lg">
								<label for="project[start_date]" class="control-label">Data Inicial</label>
								<input type="date" class="form-control" id="project[start_date]" name="project[start_date]" required>
							</div>

							<div class="form-group form-group-lg">
								<label for="project[final_date]" class="control-label">Data Final</label>
								<input type="date" class="form-control" id="project[final_date]" name="project[final_date]" required>
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary">Criar projeto</button>
				</div>
			</form>
		</div>
	</div>
</div>

<!-- Old code -->
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>Idle Tasks Count</th>
			<th>Users Count</th>
			<th>Start date</th>
			<th>Final date</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @projects.each do |project| %>
			<tr>
				<td><%= project.name %></td>
				<td><%= project.description %></td>
				<td><%= project.tasks.idle.count %></td>
				<td><%= project.users.count %></td>
				<td><%= project.start_date %></td>
				<td><%= project.final_date %></td>
				<td><%= link_to 'Show', project_tasks_path(project_id: project) %></td>
				<td><%= link_to 'Edit', edit_project_path(project) %></td>
				<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 center">
			<h1>Novo projeto</h1>
		</div>
	</div>
</div>

<button data-toggle="modal" data-target="#myModal">Modal</button>

<div class="modal fade" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="/" method="post">
				<!-- <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Novo projeto</h4>
				</div> -->
				<div class="modal-body">
					<div class="row">
						<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
						<div class="col-md-12">
							<div class="form-group form-group-lg label-floating">
								<label for="project[name]" class="control-label">Título do Projeto</label>
								<input type="text" class="form-control" id="project[name]" name="project[name]">
							</div>

							<div class="form-group label-floating">
								<label for="project[description]" class="control-label">Descrição</label>
								<textarea id="project[description]" name="project[description]" class="form-control"></textarea>
							</div>
						</div>

						<div class="col-md-6 col-md-offset-6">
							<div class="form-group form-group-lg">
								<label for="project[initial-date]" class="control-label">Data Inicial</label>
								<input type="date" class="form-control" id="project[initial-date]" name="project[initial-date]">
							</div>

							<div class="form-group form-group-lg">
								<label for="project[final-date]" class="control-label">Data Inicial</label>
								<input type="date" class="form-control" id="project[final-date]" name="project[final-date]">
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary">Criar projeto</button>
				</div>
			</form>
		</div>
	</div>
</div>

<%= link_to 'Back', projects_path %>

app/views/projects/report.html.erb
<div class=container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <div class="well">
        <% if @tasks.with_report.count > 0 %>
            <% @tasks.with_report.each do |task| %>
              <h3><%= task.name%></h3>
              <p><%= task.task_report%></p>
            <% end %>
        <%else%>
            <d>Não há atividades com relatórios individuais para gerar um relatório final</d>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid">
	<div class="row">
		
		<section class="col-md-3">
			<div class="well">
				<a data-toggle="modal" href="#options-modal" id="project-name"><h2><%= @project.name %></h2></a>
				<p><%= @project.description %></p>

				<div class="progress">
					<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow=<%= @project.progress_percent %> aria-valuemin="0" aria-valuemax="100" style="width: <%= @project.progress_percent %>%">
					</div>
				</div>

				<p>Data inicial: <%= @project.start_date.to_s(:pt_br) %></p>
				<p>Data final: <%= @project.final_date.to_s(:pt_br) %></p>

				<h4>Membros</h4>
				<ul class="list-group">
					<% @project.users.each do |user| %>
						<li class="list-group-item">
							<%= user.full_name %>
						</li>
					<% end %>
				</ul>
			</div>
		</section>
		
		<div class="col-md-9">
			<div class="row">
				
				<section class="col-md-6">
					<div class="well">
						<h3>Minhas atividades</h3>
						<table class="table">
							<thead>
								<tr>
									<th>ATIVIDADE</th>
									<th>PRAZO</th>
								</tr>
							</thead>
							<tbody>
								<% @tasks.by_user(current_user).each do |task| %>
									<tr>
										<td> <a class="task" data-toggle="modal" href="" data-task=<%= task.id %> data-project=<%= @project.id %>><%= task.name %></a> </td>
										<td><%= task.final_date.to_s(:pt_br) %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<% if @tasks.by_user(current_user).count <= 0 %>
							<p>Nenhuma atividade cadastrada</p>
						<% end %>
					</div>
				</section>
				
				<section class="col-md-6">
					<div class="well">
						<h3>Atividades ociosas</h3>
						<table class="table">
							<thead>
								<tr>
									<th>ATIVIDADE</th>
									<th>PRAZO</th>
								</tr>
							</thead>
							<tbody>
								<% @tasks.idle.each do |task| %>
									<tr>
										<td> <a class="task" data-toggle="modal" href="" data-task=<%= task.id %> data-project=<%= @project.id %>><%= task.name %></a> </td>
										<td><%= task.final_date.to_s(:pt_br) %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<% if @tasks.idle.count <= 0 %>
							<p>Nenhuma atividade cadastrada</p>
						<% end %>
					</div>
				</section>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="well">
						<h3>Outras atividades</h3>
						<table class="table">
							<thead>
								<tr>
									<th>ATIVIDADE</th>
									<th>PRAZO</th>
								</tr>
							</thead>
							<tbody>
								<% @tasks.not_by_user(current_user).each do |task| %>
									<tr>
										<td> <a class="task" data-toggle="modal" href="" data-task=<%= task.id %> data-project=<%= @project.id %>><%= task.name %></a></td>
										<td><%= task.final_date.to_s(:pt_br) %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<% if @tasks.not_by_user(current_user).count <= 0 %>
							<p>Nenhuma atividade cadastrada</p>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Create Task -->

<% if !@project.finished %>
	<a data-toggle="modal" href="#new-task-modal" class="btn btn-danger btn-fab floating-btn">
		<i class="material-icons">add</i><div class="ripple-container"></div>
	</a>
<% end %>


<div class="modal fade" id="new-task-modal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action= <%= project_tasks_path(@project) %> method="post">
				<!-- <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Novo projeto</h4>
				</div> -->
				<div class="modal-body">
					<div class="row">
						<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
						<div class="col-md-12">
							<div class="form-group form-group-lg label-floating">
								<label for="task[name]" class="control-label">Título da Atividade</label>
								<input type="text" class="form-control" id="task[name]" name="task[name]">
							</div>

							<div class="form-group label-floating">
								<label for="task[description]" class="control-label">Descrição</label>
								<textarea id="task[description]" name="task[description]" class="form-control"></textarea>
							</div>
						</div>

						<div class="col-md-6">

							<div class="form-group form-group-lg">
								<% @project.users.each do |member|%>
									<div class="checkbox">
										<label>
											<input type="checkbox" value=<%= "#{member.id}" %> name="task[list_members][]">
											<%= member.full_name %>
										</label>
									</div>
								<% end %> 
							</div>
						</div>

						<div class="col-md-6">

							<div class="form-group form-group-lg">
								<label for="task[final_date]" class="control-label">Data Inicial</label>
								<input type="date" class="form-control" id="task[final_date]" name="task[final_date]">
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary">Criar projeto</button>
				</div>
			</form>
		</div>
	</div>
</div>

<!-- Edit Task -->

<div class="modal fade" id="edit-task-modal">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<form action= <%= project_tasks_path(@project) %> method="post">
				<!-- <div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Novo projeto</h4>
				</div> -->
				<div class="modal-body">
					<div class="row">
						<input type="hidden" name="_method" value="patch">
						<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
						<div class="col-md-12">
							<div class="form-group form-group-lg label-floating">
								<label for="edit-task[name]" class="control-label">Título da Atividade</label>
								<input type="text" class="form-control" id="task-name-input" name="task[name]">
							</div>

							<div class="form-group label-floating">
								<label for="task[description]" class="control-label">Descrição</label>
								<textarea id="task-description-input" name="task[description]" class="form-control"></textarea>
							</div>
						</div>

						<div class="col-md-6">

							<div class="form-group form-group-lg">
								<% @project.users.each do |member|%>
									<div class="checkbox">
										<label>
											<input class="task-list-member-input" type="checkbox" value=<%= "#{member.id}" %> name="task[list_members][]">
											<%= member.full_name %>
										</label>
									</div>
								<% end %> 
							</div>
						</div>

						<div class="col-md-6">

							<div class="form-group form-group-lg">
								<label for="task[final_date]" class="control-label">Data Inicial</label>
								<input type="date" class="form-control" id="task-date-input" name="task[final_date]">
							</div>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
					<button type="submit" class="btn btn-primary">Salvar alterações</button>
				</div>
			</form>
		</div>
	</div>
</div>


<!-- Project info modal -->
<div class="modal fade" id="options-modal">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">

				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h4 class="modal-title">Opções de projeto</h4>
				</div>

				<div class="modal-body">
					<div class="row">
						<div class="col-md-12">
							<% if !@project.finished %>
								<!-- <button class="btn btn-danger btn-raised"></button> -->
								<%= link_to "Gerar relatório", project_report_path(@project), {class: 'btn btn-success btn-raised'}%>
								<%= button_to "Arquivar projeto", project_finish_path(@project), {class: 'btn btn-danger btn-raised'}%>
							<% else %>
								<button class="btn btn-danger btn-raised">Desarquivar projeto</button>
							<% end %>
						</div>
					</div>
				</div>

		</div>
	</div>
</div>


<!-- Old code -->
<p>
<%= link_to 'New Task', new_project_task_path(@project) %>
</p>

<p>
	<strong>Name:</strong>
	<%= @project.name %>
</p>

<p>
	<strong>Description:</strong>
	<%= @project.description %>
</p>

<p>
	<strong>Start date:</strong>
	<%= @project.start_date %>
</p>

<p>
	<strong>Final date:</strong>
	<%= @project.final_date %>
</p>

<p>
	Tasks count: <%= @tasks.count %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<script type="text/javascript">

	var currentTask = null;
	var baseActionPath = null;

	$('a.task').on('click', function (event) {
		var button = $(this); // Button that triggered the modal
		var taskId = button.data('task');
		var projectId = button.data('project');

		getTaskInfo(projectId, taskId);

		$('#edit-task-modal').modal('show');
	})

	function getTaskInfo(projectId, taskId) {
		var xhr = new XMLHttpRequest();
		var requestUrl = '/' + projectId + '/tasks/' + taskId + '.json';
		xhr.open('GET', requestUrl, true);
		xhr.setRequestHeader("Content-type", "text/json");
		xhr.send();

		xhr.addEventListener('readystatechange', function() {
			if (xhr.readyState == 4 && xhr.status == 200) {
				var response = JSON.parse(xhr.responseText);

				fillTaskInfo(response["task"]);
			}
		});

		currentTask = taskId;
	}

	function fillTaskInfo(task) {
		var form = $('#edit-task-modal form');
		if (baseActionPath == null) {
			baseActionPath = form.attr('action');
		}
		var newAction = baseActionPath + '/' + task['id'];
		form.attr('action', newAction);

		var taskName = task["name"];

		var nameElem = $("#task-name-input");
		nameElem.parent().removeClass('is-empty');
		nameElem.val(taskName);

		var descElem = $("#task-description-input");
		descElem.parent().removeClass('is-empty');
		descElem.val(taskName);

		var membersIDs = [];
		for (var i=0; i<task["users"].length; i++){
			membersIDs.push(""+task["users"][i]['id'])
		}
		// console.log(task["users"][0]["id"]);
		var memberElems = $(".task-list-member-input");
		for (var i=0; i<memberElems.length; i++){
			var memberElem = memberElems[i];

			if (membersIDs.indexOf(memberElem.value) >= 0){
				memberElem.checked = true;
			}

		}

		var nameElem = $("#task-date-input");
		nameElem.parent().removeClass('is-empty');
		nameElem.val(task["final_date"]);
	}

</script>